### ISSUE TITLE
可能需要个信息提示页面

### ISSUE THREAD

**Issue by ChiruMori** [nekoMC/NekoSite#1]
**问题**：用户点击邮箱中的激活链接后，无论是否成功都只能看到JSON的响应结果。后端不提供页面展示，需要主站配合。
**改进思路**：后端处理后，将请求重定向到统一的提示页面，将要提示的内容会作为参数传递过来
- - -
比如：
+ 操作成功后，后端将请求重定向到 `https://www.nekomc.fun/message?status=0&content=账号已激活`
+ 操作失败后，后端将请求重定向到 `https://www.nekomc.fun/message?status=1&content=链接已被使用`

这个是只举例，参数、URL 随意，看主站这边的需要。

**Comment by Cloudkkk** [comment]
加入/message路由
目前只加入status和content参数
操作成功 status=0 ,content 作为提示信息展示
操作失败 status !=0,content同样作为提示信息展示

**Comment by ChiruMori** [comment]
消息字段解释：
```Java
    @ApiModelProperty("状态码，0失败，1成功")
    private Integer state;

    @ApiModelProperty("提示页标题，如“绑定失败”")
    private String title;

    @ApiModelProperty("需要展示的信息，可能会内嵌一段 html 代码，如“认证成功，点击<a href=\"#\">某链接</a>进行绑定”")
    private String message;
```

消息格式如图所示（base64 编码）：
![image](https://user-images.githubusercontent.com/34133704/147875104-26410d8f-d13a-4c84-9a8f-49db24943ef5.png)
