### ISSUE TITLE
基岩版用户，自动加前缀

### ISSUE THREAD

**Issue by ChiruMori** [nekoMC/NekoSite#2]
**问题**：注册时，用户不手动添加 `[BE]` 前缀的话，注册的账号会是 Java 版的账号
**改进思路**：添加一个默认勾选的复选框，选择时为用户名添加 `[BE]` 前缀，或者任何合理的方案。
- - -
后端暂时没有针对用户名的校验，下次修改会加入正则校验：`^(\[BE\]){0,1}\w+$`

**Comment by Cloudkkk** [comment]
加入select下拉框选择BE/Java端
BE端username添加[BE]前缀

**Comment by ChiruMori** [comment]
因注册时发现了玩家名过长导致的 BUG，将判定的正则修改为 `^(\[BE])?\w{1,16}$`
