### ISSUE TITLE
正版账号注册成功界面网址显示出错

### ISSUE THREAD

**Issue by ourange** [nekoMC/NekoSite#5]
正版账号注册成功后的界面，网址的显示出错。网址的html标签显示了出来。

**Comment by first-snow** [comment]
后端重定向回传参数如下
+ title：喵服 - 邮箱验证
+ content：即将完成！请点击<a href="https://api.nekomc.fun/neko/users/confirmEmail?data=eyJlbWFpbCI6ImN4bG0zQGN4bG0ud29yayIsInVpZCI6NTF9&signature=ac293eef10badf7df77f1a5a369c2d95">验证链接</a>完成您邮箱的验证，然后开启喵服生活吧！
+ username：ChiruMoriii

**Comment by ourange** [comment]
您好，这是下线自动回复邮件！
 
您好，我现在不在线，在我上线之后，我会尽快给您回复
